### ISSUE TITLE
problem with areachart javafx

### ISSUE THREAD

**Issue by gusttavosouza** [victorlaerte/javafx-asynctask#7]
I implemented this class in my javaFx and found it excellent, I can get my Stage normally, very good indeed! The only problem is that when I try to get a value from the Thread created and insert into a graphic that is in the GUI thread it gives a problem.

![image](https://user-images.githubusercontent.com/22873208/50724897-ed804700-10db-11e9-8762-19292d8704f2.png)

**Comment by victorlaerte** [comment]
If you want to manipulate your GUI this has to be done in JavaFx main thread.
The methods that execute on the main thread are preExecute, postExecute or publishProgress. If none of these works for you, you'll have to force this by using `Platform.runLater(() -> `
