### ISSUE TITLE
Can run JUnit test 

### ISSUE THREAD

**Issue by yemikudaisi** [victorlaerte/javafx-asynctask#8]
I'm unable to run maven JUnit test without loading JavaFX because of these lines of codes in ``execute()`` method:

    Platform.runLater(() -> {
	onPreExecute();
	backGroundThread.setDaemon(daemon);
        backGroundThread.start();
    });

Anyway, I eventually got it to work by replacing the above with (this also makes it more convenient to run long tasks):

    Task task = new Task<Void>() {
        @Override public Void call() {
	    onPreExecute();
	    backGroundThread.setDaemon(daemon);
	    backGroundThread.start();
	    return null;
	}
    };
    new Thread(task).start();

Does the change have any other implications I need to be aware of ?

**Comment by victorlaerte** [comment]
Hey @yemikudaisi, I think in the way you implemented this to solve your problem `preExecute` will never run in the JavaFX UI thread, so if you try to update some UI component in `onPreExecuted()` you will get an Exception.

The code you removed solved your problem, but it changes the purpose of the library that is to run `onPreExecute` and `onPostExecute` in JavaFX UI Thread.

**Comment by yemikudaisi** [comment]
> The code you removed solved your problem, but it changes the purpose of the library that is to run `onPreExecute` and `onPostExecute` in JavaFX UI Thread.

@victorlaerte  Now I get it, thanks for the heads up, do I have to implement another version for unit testing (I really don't want to worry about JavaFX dependencies for unit testing) ?

**Comment by victorlaerte** [comment]
It's hard to say without the whole context, but I believe you should concentrate your test in the minimum unit of code, so if it's possible to test on the logic inside each method `onPreExecute`, `doInBackground` and `onPostExecute` I would do this.

**Comment by yemikudaisi** [comment]
> so if it's possible to test on the logic inside each method `onPreExecute`, `doInBackground` and `onPostExecute` I would do this.

This should work, thanks.
